spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uc
          uri: lb://user-center
          predicates:
            - Path=/api/pub/user/**,/api/mgt/user/**
          filters:
            - name: CircuitBreaker
        - id: cms
          uri: lb://cms-center
          predicates:
            - Path=/api/pub/cms/**,/api/mgt/cms/**
          filters:
            - name: CircuitBreaker
        - id: stats
          uri: lb://stats-center
          predicates:
            - Path=/api/pub/stats/**,/api/mgt/stats/**
          filters:
            - name: CircuitBreaker