spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uc
          uri: lb://user-center
          predicates:
            - Path=/uc/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker